/* Generated By:JavaCC: Do not edit this line. SiliTreeConstants.java Version 5.0 */
package LEDscript2.parser;

public interface SiliTreeConstants
{
  public int JJTCODE = 0;
  public int JJTSTATEMENT = 1;
  public int JJTBLOCK = 2;
  public int JJTPARMLIST = 3;
  public int JJTFNBODY = 4;
  public int JJTFNDEF = 5;
  public int JJTRETURNEXPRESSION = 6;
  public int JJTVOID = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTADDASSIGN = 9;
  public int JJTDECASSIGN = 10;
  public int JJTMULTIASSIGN = 11;
  public int JJTDIVASSIGN = 12;
  public int JJTFLIPASSIGN = 13;
  public int JJTCLEAR = 14;
  public int JJTFILL = 15;
  public int JJTDELAY = 16;
  public int JJTUPDATE = 17;
  public int JJTINFO = 18;
  public int JJTLEDS = 19;
  public int JJTWRITE = 20;
  public int JJTSAVE = 21;
  public int JJTIFSTATEMENT = 22;
  public int JJTFORLOOP = 23;
  public int JJTCALL = 24;
  public int JJTARGLIST = 25;
  public int JJTOR = 26;
  public int JJTAND = 27;
  public int JJTCOMPEQUAL = 28;
  public int JJTCOMPNEQUAL = 29;
  public int JJTCOMPGTE = 30;
  public int JJTCOMPLTE = 31;
  public int JJTCOMPGT = 32;
  public int JJTCOMPLT = 33;
  public int JJTADD = 34;
  public int JJTSUBTRACT = 35;
  public int JJTTIMES = 36;
  public int JJTDIVIDE = 37;
  public int JJTUNARYNOT = 38;
  public int JJTUNARYPLUS = 39;
  public int JJTUNARYMINUS = 40;
  public int JJTFNINVOKE = 41;
  public int JJTIDENTIFIER = 42;
  public int JJTDEREFERENCE = 43;
  public int JJTCHARACTER = 44;
  public int JJTINTEGER = 45;
  public int JJTRATIONAL = 46;
  public int JJTTRUE = 47;
  public int JJTFALSE = 48;


  public String[] jjtNodeName = {
    "Code",
    "Statement",
    "Block",
    "Parmlist",
    "FnBody",
    "FnDef",
    "ReturnExpression",
    "void",
    "Assignment",
    "Addassign",
    "Decassign",
    "Multiassign",
    "Divassign",
    "flipassign",
    "Clear",
    "Fill",
    "Delay",
    "Update",
    "Info",
    "Leds",
    "Write",
    "Save",
    "IfStatement",
    "ForLoop",
    "Call",
    "ArgList",
    "Or",
    "And",
    "CompEqual",
    "CompNequal",
    "CompGTE",
    "CompLTE",
    "CompGT",
    "CompLT",
    "Add",
    "Subtract",
    "Times",
    "Divide",
    "UnaryNot",
    "UnaryPlus",
    "UnaryMinus",
    "FnInvoke",
    "Identifier",
    "Dereference",
    "Character",
    "Integer",
    "Rational",
    "True",
    "False",
  };
}
/* JavaCC - OriginalChecksum=ee0ecd919a6f92ee7ce43eb396da0227 (do not edit this line) */
